# Generated by Django 3.2.3 on 2021-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pnum',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='상품코드'),
        ),
    ]
