# Generated by Django 3.2.3 on 2021-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_pnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pnum',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='상품코드'),
        ),
    ]
