# Generated by Django 3.2.3 on 2021-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('tel', models.CharField(max_length=15, unique=True, verbose_name='핸드폰')),
                ('name', models.CharField(max_length=15, verbose_name='이름')),
                ('birth', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=5, verbose_name='성별')),
                ('address', models.CharField(choices=[('경기도', '경기도'), ('강원도', '강원도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주도', '제주도')], max_length=10, verbose_name='시')),
                ('style', models.CharField(choices=[('하객룩', '하객룩'), ('데일리', '데일리'), ('오피스', '오피스'), ('캐주얼', '캐주얼'), ('스트릿', '스트릿'), ('기타', '기타')], max_length=20, verbose_name='옷 스타일')),
                ('job', models.CharField(choices=[('학생', '학생'), ('주부', '주부'), ('전문직', '전문직'), ('회사원', '회사원'), ('자영업', '자영업'), ('기타', '기타')], default=6, max_length=30, verbose_name='직업')),
            ],
        ),
    ]
