# Generated by Django 3.2.3 on 2021-06-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('product', '0002_alter_product_pnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('onum', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='주문번호')),
                ('quan', models.IntegerField(unique=True, verbose_name='수량')),
                ('totp', models.IntegerField(unique=True, verbose_name='총 주문금액')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='member.sign', verbose_name='이름')),
                ('prod_num', models.ForeignKey(db_column='prod_num', on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품코드')),
            ],
        ),
    ]
