# Generated by Django 3.2.3 on 2021-06-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210604_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totp',
        ),
    ]
