# Generated by Django 3.2.3 on 2021-06-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0003_remove_order_totp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('bnum', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='구매번호')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.sign', verbose_name='이름')),
                ('onum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='장바구니번호')),
            ],
        ),
    ]
