# Generated by Django 3.2.3 on 2021-06-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210611_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='onum',
            field=models.CharField(max_length=100, verbose_name='장바구니번호'),
        ),
    ]
