# Generated by Django 3.2.3 on 2021-06-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0007_alter_buy_onum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='member.sign', verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='onum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.order', verbose_name='장바구니번호'),
        ),
    ]
