# Generated by Django 3.2.3 on 2021-06-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0008_auto_20210611_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.sign', verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='onum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='장바구니번호'),
        ),
    ]
