# Generated by Django 3.2.3 on 2021-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210611_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='onum',
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.CharField(max_length=100, null=True, verbose_name='장바구니번호'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='member',
            field=models.CharField(max_length=100, null=True, verbose_name='이름'),
        ),
    ]
