# Generated by Django 3.2.3 on 2021-06-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210612_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='product',
        ),
        migrations.AddField(
            model_name='buy',
            name='pname',
            field=models.CharField(max_length=100, null=True, verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='buy',
            name='pnum',
            field=models.IntegerField(null=True, verbose_name='상품코드'),
        ),
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.IntegerField(null=True, verbose_name='상품명'),
        ),
    ]
