# Generated by Django 3.2.3 on 2021-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210612_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='quan',
            field=models.IntegerField(null=True, verbose_name='개수'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.IntegerField(null=True, verbose_name='가격'),
        ),
    ]
