# Generated by Django 3.2.3 on 2021-06-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('product', '0002_alter_product_pnum'),
        ('order', '0012_auto_20210612_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='추천상품번호')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.sign', verbose_name='아이디')),
            ],
        ),
    ]
