# Generated by Django 3.2.3 on 2021-06-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='user_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='recommend',
            old_name='pnum',
            new_name='product',
        ),
    ]
