# Generated by Django 3.2.3 on 2021-06-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_pnum'),
        ('order', '0016_auto_20210615_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='추천상품번호'),
        ),
    ]
