# Generated by Django 3.2.3 on 2021-06-22 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_recommend_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='pay',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='주문날짜'),
            preserve_default=False,
        ),
    ]
